export const translations = {
  th: {
    dashboard: 'แผงควบคุม',
    inventory: 'คลังอุปกรณ์',
    borrow: 'ยืม-คืน',
    admin: 'ผู้ดูแลระบบ',
    logout: 'ออกจากระบบ',
    welcome: 'ยินดีต้อนรับ',
    total_devices: 'อุปกรณ์ทั้งหมด',
    available: 'ว่าง',
    borrowed: 'ถูกยืม',
    maintenance: 'ซ่อมบำรุง',
    loading: 'กำลังโหลด...',
    login: 'เข้าสู่ระบบ',
    username: 'ชื่อผู้ใช้',
    password: 'รหัสผ่าน',
    back: 'กลับ',
    start: 'เริ่มต้นใช้งาน',
    admin_login: 'เข้าสู่ระบบผู้ดูแล',
    db_connected: 'เชื่อมต่อฐานข้อมูลแล้ว',
    db_disconnected: 'ไม่ได้เชื่อมต่อฐานข้อมูล',
    service: 'แจ้งซ่อม',
    logs: 'ประวัติการใช้งาน',
  },
  en: {
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    borrow: 'Borrow-Return',
    admin: 'Admin Panel',
    logout: 'Logout',
    welcome: 'Welcome',
    total_devices: 'Total Devices',
    available: 'Available',
    borrowed: 'Borrowed',
    maintenance: 'Maintenance',
    loading: 'Loading...',
    login: 'Login',
    username: 'Username',
    password: 'Password',
    back: 'Back',
    start: 'Get Started',
    admin_login: 'Admin Login',
    db_connected: 'Database Connected',
    db_disconnected: 'Database Disconnected',
    service: 'Repair Service',
    logs: 'Activity Logs',
  }
};
